version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.1
    env_file:
      - .env
    # environment:
    #   - POSTGRES_DB=tictactoedb
    #   - POSTGRES_USER=tictactoe.user
    #   - POSTGRES_PASSWORD=tictactoe.password
    #   - POSTGRES_PORT=5432
    #   - POSTGRES_HOST=postgres
    volumes:
      - .postgresdb/:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure

  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - backend_migrate
    links:
      - postgres

  backend_migrate:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/code
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  .postgresdb: