# Generated by Django 3.1.3 on 2020-11-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20201125_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
    ]
