# Generated by Django 3.1.3 on 2020-11-25 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_auto_20201125_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=['-', '-', '-', '-', '-', '-', '-', '-', '-'], max_length=1), size=3),
        ),
    ]
