# Generated by Django 3.1.3 on 2020-11-25 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_auto_20201125_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), default=['-', '-', '-', '-', '-', '-', '-', '-', '-'], size=3),
        ),
    ]
