# Generated by Django 3.1.3 on 2020-11-25 09:18

import django.contrib.postgres.fields
from django.db import migrations, models
import game_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_auto_20201125_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), default=game_app.models.Game.get_callable_board, size=9),
        ),
    ]
