# Generated by Django 3.1.3 on 2020-11-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0011_auto_20201125_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
